KEYWORDS = [
    '"oil tanker"',
    '"crude oil"',
    '"oil shipment"',
    '"oil terminal"',
    "petroleum",
    "refinery",
    "OPEC",
    '"fuel import"',
    '"Bangladesh fuel"',
    '"Bangladesh Petroleum Corporation"',
    "BPC",
    '"Jamuna Oil"',
    '"Padma Oil"',
    '"Meghna Petroleum"',
    "LPG",
    "diesel",
    "petrol",
    "aviation fuel",
    "fuel cargo",
    "energy market"
]
