name: Oil Tanker Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Telegram
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.CHAT_ID }}" \
          -d text="✅ GitHub Actions সফলভাবে চলছে!"
